# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 768a3fa253f62ea6522f77c7c0dc5c20771006a6405ab920da06329000e717e1e8380b761c09efe76b4e2bca3dd2ba971eb73deeb3c5bc04def9f92c2ffc90b9

test:
  secret_key_base: ec865a441fac390c811796e6def084c4dafd9a8a409684e0d1b0c4dba3d6b3ebf48b4bccafcecbfc2d402ff58f3acc6f5b3753551743baa1c6a4f77bd3e2a6ff

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
